mySite/headPage/urls.py
from django.urls import path
from headPage import views
#empty

mySite/mySite/urls.py
from django.contrib import admin
from django.urls import include, path
from headPage.views import MyView, MyIndexView, MySectionView, MyArticleView, MyTovarView, MyWindyView, MyTest

urlpatterns = [    
    path('', MyView.as_view()),
    path('admin/', admin.site.urls),
    path('index/', MyIndexView.as_view()),
    path('tovar/', MyTovarView.as_view()),
    path('windy/', MyWindyView.as_view()),
]

mySite/headPage/models.py
from django.db import models
from django.contrib.auth.models import User

class Section(models.Model):
    class Meta:
        db_table = "section"
 
    section_title = models.CharField(max_length=200, default='DEFAULT')
    section_url = models.CharField(max_length=50)
    section_description = models.TextField()
 
    def title(self):
        return self.section_title

class Article(models.Model):
    class Meta:
        db_table = "article"
 
    article_title = models.CharField(max_length=200)
    article_section = models.ForeignKey(Section, on_delete=models.CASCADE,)
    article_author = models.ForeignKey(User, on_delete=models.CASCADE,)
    article_date = models.DateTimeField('Дата публикации')
    article_content = models.TextField()
    article_status = models.IntegerField()
 
    def title(self):
        return self.article_title

class Book(models.Model):
    header = models.CharField(max_length=200, help_text='Заголовок', blank=False,)
    description = models.TextField(help_text='Описание', blank=False,)

class Tovar(models.Model):
    class Meta:
        db_table = "tovar"
    
    name = models.CharField(max_length=200)
    discript = models.TextField()
    cost = models.IntegerField()

class MyMenu(models.Model):
    class Meta:
        db_table = "mymenu"
        ordering = ["l1"]

    l1 = models.DecimalField(max_digits=3, decimal_places=0)
    l2 = models.DecimalField(max_digits=3, decimal_places=0)
    l3 = models.DecimalField(max_digits=3, decimal_places=0)
    l4 = models.DecimalField(max_digits=3, decimal_places=0)
    l5 = models.DecimalField(max_digits=3, decimal_places=0)
    first = models.BooleanField()
    visible = models.BooleanField()
    content = models.CharField(max_length=200)
    level = models.DecimalField(max_digits=3, decimal_places=0)
    link = models.CharField(max_length=200)
    activ = models.BooleanField()

mySite/headPage/forms.py
#from django.db import models
#from .forms import forms
from django import forms

import cgi 

storage = cgi.FieldStorage()
data = storage.getvalue('data')
print('Status: 200 OK')
print('Content-Type: text/plain')
print('')
if data is not None:
    print(data)

class BookForm(forms.Form):
    class Meta:
        db_table = "form"
        fields = '__all__'

class UserForm(forms.Form):
    name = forms.CharField()
    age = forms.IntegerField()

class TovarForm(forms.Form):
    name = forms.CharField()
    discript = forms.CharField()
    cost = forms.IntegerField()

    def getName(self):
        name = self.name
        return name

mySite/headPage/views.py
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.views import View
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.db.models.query_utils import DeferredAttribute
from django.views.generic.list import ListView
from django.http import Http404
from django.urls import reverse
from screeninfo import get_monitors

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import UpdateView
from django.contrib.auth.views import LoginView

from .forms import UserForm, BookForm, TovarForm

from .models import Section, Article, Tovar, MyMenu, User

import datetime
import random

class MyView(View):
    menuModel = MyMenu
    articleModel = Article
    userForm = UserForm
    bookForm = BookForm
    template_name = 'headPage.html'
    context_object_name = 'articles'

    def post(self, request, *args, **kwargs):
        id =  request.POST.get('id')
        l1 =  request.POST.get('l1')
        l2 =  request.POST.get('l2')
        l3 =  request.POST.get('l3')
        l4 =  request.POST.get('l4')
        l5 =  request.POST.get('l5')
        first =  request.POST.get('first')
        visible =  request.POST.get('visible')
        level =  request.POST.get('level')
        content =  request.POST.get('content')
        link =  request.POST.get('link')
        #установка всех visible в 0
        self.menuModel.objects.all().update(visible=0)
        self.menuModel.objects.all().update(first=0)
        self.menuModel.objects.all().update(activ=0)
        #обновление данных в базе данных
        # 1 уровень
        if l2 == '0':
            for x in range(1,(int(level) + 2)):
                self.menuModel.objects.all().filter(level=x).filter(l1=l1).update(visible=1)
        # 2 уровень
        elif l3 == '0':
            self.menuModel.objects.all().filter(l1=l1).filter(l3='0').update(first=1)
            for x in range(1,(int(level) + 2)):
                self.menuModel.objects.all().filter(level=x).filter(l2=l2).filter(l1=l1).update(visible=1)
        # 3 уровень
        elif l4 == '0':
            self.menuModel.objects.all().filter(l1=l1).filter(l3='0').update(first=1)
            for x in range(1,(int(level) + 2)):
                self.menuModel.objects.all().filter(level=x).filter(l3=l3).filter(l2=l2).filter(l1=l1).update(visible=1)
        # 4 уровень
        else:
            self.menuModel.objects.all().filter(l1=l1).filter(l3='0').update(first=1)
            for x in range(1,(int(level) + 2)):
                self.menuModel.objects.all().filter(level=x).filter(l3=l3).filter(l3=l3).filter(l2=l2).filter(l1=l1).update(visible=1)
        self.menuModel.objects.all().filter(id=id).update(activ=1)
        return render(request, self.template_name, context=self.fun(link))

    def get(self, request, *args, **kwargs):
        link = self.menuModel.objects.all().get(activ=1)
        return render(request, self.template_name, context=self.fun(link.link))

    def fun(self, link):
        randomNum1 = random.randint(0, 30)
        randomNum2 = random.randint(0, 100) 
        randomNum3 = random.randint(0, 100)
        try:
            menu = self.menuModel.objects.all()
            articles = self.articleModel.objects.all()  
        except Exception:
            raise Http404("ОШИБКА ЧТЕНИЯ ИЗ БАЗЫ ДАННЫХ")
        rend = self.articleModel.objects.count()
        context = {"link": link,"latest_firstPage": randomNum2, "var_1" : randomNum3, "range": range(randomNum1), "rend" : rend, 'articles':articles, 'userForm':self.userForm, 'bookForm':self.bookForm, 'menu':menu}
        return context

    def my_view(self, request):
        if not request:
            return HttpResponseNotFound('<h1>Page not found</h1>')
        else:
            return HttpResponse('<h1>Page was found</h1>')
        
        return HttpResponse(status=2001)

    @staticmethod
    def current_datetime():
        now = datetime.datetime.today()
        html = "<html><body><br> It is now: %s.</body></html>" % now
        return html

class MyIndexView(View):
    tovar = Tovar
    form = UserForm
    template_name = 'index.html'
    context_object_name = 'sections'
 
    def get(self, request, *args, **kwargs):
        tovars = self.tovar.objects.all()
        count = self.tovar.objects.count()
        context = {'tovars':tovars,'count':count,'form':self.form} 
        return render(request, self.template_name, context=context)
 
class MySectionView(View):
    template_name = 'headPage/section.html'
 
    def get(self, request, *args, **kwargs):
        context = {}
        section = get_object_or_404(Section, section_url=self.kwargs['section'])
        
        context['section'] = section
 
        return render(request, template_name=self.template_name, context=context)
  
class MyArticleView(View):
    template_name = 'headPage/article.html'
 
    def get(self, request, *args, **kwargs):
        context = {}
        article = get_object_or_404(Article, id=self.kwargs['article_id'])
        
        context['article'] = article
 
        return render(request, template_name=self.template_name, context=context)

class MyTovarView(View):    
    tovar = Tovar
    form = TovarForm
    template_name = 'tovar.html'
    context_object_name = 'tovar'
 
    def get(self, request, *args, **kwargs):
        context = {'id':-1, 'form':self.form,} 
        return render(request, self.template_name, context=context)
    
    def post(self, request, *args, **kwargs):
        discript =  request.POST.get('discript')
        cost =  request.POST.get('cost')
        name =  request.POST.get('name')
        if (self.baseCheck(name)):
            b = self.tovar(name=name, discript=discript, cost=cost,)
            b.save()
            context = {'name':name, 'discript':discript, 'cost':cost, 'id':1, 'form':self.form,} 
        else:
            context = {'id':0, 'form':self.form,}
        return render(request, self.template_name, context=context)
    
    def baseCheck (self, name):
        #проверка наличия записи с таким названием в базе
        if (self.tovar.objects.filter(name=name)):
            return False
        return True

class MyWindyView(UpdateView):
    template_name = 'windy.html'
    context_object_name = 'windy'

    def get(self, request, *args, **kwargs):        
        obj = self
        username = request.user.username
        if username != '':
            first_name = request.user.first_name
            last_name = request.user.last_name
            email = request.user.email
            password = request.user.password
            groups = request.user.groups
            user_permissions = request.user.user_permissions
            is_staff = request.user.is_staff
            is_active = request.user.is_active
            is_superuser = request.user.is_superuser
            last_login = request.user.last_login
            user = {username, first_name, last_name, email, password, groups, user_permissions, is_staff, is_superuser, is_active, last_login,}
        else:
            user = {'НЕТ ДАННЫХ'}
        context = {'obj': obj, 'LoginRequiredMixin': LoginRequiredMixin, 'UpdateView': UpdateView, 'user': user, 'username': username, 'reg': True, }
        if self.test(username):
            try:
                return render(request, self.template_name, context=context) 
            except Exception:
                context = {'user': user, 'reg': False}
                return render(request, self.template_name, context=context)
                #raise Http404("ОШИБКА ДОСТУПА ПОЛЬЗОВАТЕЛЯ")
        else:
            context = {'user': user, 'reg': False}
            return render(request, self.template_name, context=context)  

    def test(self, arg):
        if arg == '':
            return False
        return True
    
 
class MyTest(View):
    menuModel = MyMenu
    template_name = 'windy.html'
    context_object_name = 'windy'

    def post(self, request, *args, **kwargs):
        try:
            menu = self.menuModel1.objects.all()
            raise Http404("ЧТЕНИE ДАННЫХ")
        except Exception:
            raise Http404("ОШИБКА ЧТЕНИЯ ИЗ БАЗЫ ДАННЫХ")
        b = self.menu(l1=1, l2=2, l3=3, l4=4, l5=5, first=0, visible=1, level=1, content='Новый уровень')
        b.save()

mySite/headPage/templates/article.html
{% extends 'base.html' %}
{% block page %}
    <article>
        <h1>{{ article.article_title }}</h1>
        <p>{{ article.article_content|safe }}</p>
    </article>
{% endblock %}

mySite/headPage/templates/asideLeft.html
<div class="vertmenu_l" id="id">
    <script>
        initMenu();
    </script>
    <ul>
        <li>
            <a class="active_l" id="00_titul" onclick="changeFunction(this.id)">Титул</a>
            <input type="checkbox" class="subCat_l" id="00" />
            <label class="chka_l" for="00+"></label>
        </li>
        <li>
                <a class="active_l" id="01_01_chapter" onclick="changeFunction(this.id)">1 Безопасность</a>
                <input type="checkbox" class="subCat_l" id="01_01" />
                <label class="chka_l" for="01_01"></label>
                <ul style="display:none">
                    <li><a id="01_01_chapter" onclick="changeFunction(this.id)">1.1 Маркировка указаний</a></li>
                    <li><a id="01_02_chapter" onclick="changeFunction(this.id)">1.2 Целевая группа</a></li>
                    <li><a id="01_03_chapter" onclick="changeFunction(this.id)">1.3 Применение по назначению</a></li>
                    <li><a id="01_04_chapter" onclick="changeFunction(this.id)">1.4 Общие указания</a></li>
                    <li><a id="01_05_chapter" onclick="changeFunction(this.id)">1.5 Меры безопасности</a></li>
                    <li><a id="01_06_chapter" onclick="changeFunction(this.id)">1.6 Электроподключение</a></li>
                    <li><a id="01_07_chapter" onclick="changeFunction(this.id)">1.7 Изменения в конструкции</a></li>
                    <li><a id="01_08_chapter" onclick="changeFunction(this.id)">1.8 Утилизация</a></li>
                </ul>
            </li>
            <li>
                <a class="active_l" id="02_00_chapter" onclick="changeFunction(this.id)">2 Гарантии и ответственность</a>
                <input type="checkbox" class="subCat_l" id="02_00" />
                <label class="chka_l" for="02_001"></label>
                <ul style="display:none">
                </ul>
            </li>
            <li>
                <a class="active_l" id="03_01_chapter" onclick="changeFunction(this.id)">3 Общие сведения</a>
                <input type="checkbox" class="subCat_l" id="03_00" />
                <label class="chka_l" for="03_00"></label>
                <ul style="display:none">
                    <li><a id="03_01_chapter" onclick="changeFunction(this.id)">3.1 Назначение шкафа управления R-1
                            Online</a></li>
                    <li><a id="03_02_chapter" onclick="changeFunction(this.id)">3.2 Конструктивное исполнение</a></li>
                    <li><a id="03_03_chapter" onclick="changeFunction(this.id)">3.3 Применение</a></li>
                    <li><a id="03_04_chapter" onclick="changeFunction(this.id)">3.4 Структура и состав Системы RAZ</a></li>
                    <li><a id="03_05_chapter" onclick="changeFunction(this.id)">3.5 Узлы и шкафы входящие в состав Системы
                            RAZ</a></li>
                    <li><a id="03_06_chapter" onclick="changeFunction(this.id)">3.6 Режимы работы Системы RAZ</a></li>
                    <li><a id="03_07_chapter" onclick="changeFunction(this.id)">3.7 Версия инструкции</a></li>
                </ul>
            </li>
    </ul>
</div>

mySite/headPage/templates/asideRight.html
ASIDE LEFT <br>
ASIDE LEFT

mySite/headPage/templates/base.html
{% load static %}
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <!--
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    -->
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'menu.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'RAZstyle.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'newmenu.css' %}" />
    <script src="{% static 'script.js' %}"></script>
    <script src="{% static 'jquery.js' %}"></script>
    
    <!--
    <script src="{% static 'acordeon.js' %}"></script>
    <script src="{% static 'PHP/functionPHP.php' %}"></script>
    <script src="{% static 'jquery.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap4.css' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    -->
    <title>My Site Django</title>
  </head>
  <body>
    <!--верхняя часть-->
    <header>
      <div id="myHeader">
        {% block header %}        
        {% endblock header %}
      </div>
    </header>
    <!--панель навигации-->
    <nav>
      <div id="myNav">
        {% block nav %}
        {% endblock nav %}
      </div>
    </nav>
    <!--основное содержимое-->
    <div id="mySection">
      <!--левая колонка-->
      <div id="asideLeft">
        {% block asideLeft %}
        {% endblock asideLeft %}
      </div>
      <!--основное содержимое-->
      <div id="content">
          {% block content %}
          {% endblock content %}
      </div>
      <!--правая колонка-->
      <div id="asideRight" class="asideRight">
          {% block asideRight %}
          {% endblock asideRight %}
      </div>
    </div>
    <!--подвал-->
    <footer>
      <div id="myFooter">
          {% block footer %}
          {% endblock footer %}
      </div>
    </footer>
  </body>
</html>

mySite/headPage/templates/base_old.html
<!doctype html>
{% load static %}
<html lang="ru">
    <head>
    <meta charset="utf-8" />
    <title></title>
    <link rel="stylesheet" type="text/css" href="{% static 'cssHeadPage.css' %}" />
    </head>
    <body>
        <!--верхняя часть-->
        <header>
            {% block header %}
            {% endblock header %}
        </header>
        <!--панель навигации-->
        <nav>
            {% block nav %}
            {% endblock nav %}
        </nav>
        <!--основное содержимое-->
        <section>
            {% block section %}
                <article>
                    {% block article %}
                    {% endblock article %}
                </article>
                <!--правая боковая панель-->
                <aside>
                    {% block aside %}
                    {% endblock aside %}
                </aside>
            {% endblock section %}
        </section>        
        <!--подвал-->
        <footer>
            {% block footer %}
            {% endblock footer %}
        </footer>    
    </body>
</html>
<!--#empty-->

mySite/headPage/templates/footer.html
<p> ЭТО ФУТЕР </p>

mySite/headPage/templates/headPage.html
{% extends 'base.html' %}

{% block content %}
    {% if link != '0' %}
        <script>
            changeFunction('{{ link }}');
        </script>
        <div id="content">{{ link }}</div>    
    {% else %}
        <p>Запрос: {{request}}</p>
        {% if latest_firstPage > 50 %}
            <span style = "color:rgb(255,0,0)">Latest_firstPage: {{ latest_firstPage }}</span> <br>
        {% else %}
            <span style = "color:rgb(0,0,255)">Latest_firstPage: {{ latest_firstPage }}</span> <br>
        {% endif %}
        
        <span>Test.var_1: {{ var_1 }}</span> <br>
        <span>range: {{ range }}</span> <br>
        <span>Количество статей: {{ rend }}</span> <br>

        {% if latest_firstPage > 50 %}
            <p id="orangeClass">Ветка IF</p> <br>
            <span>START</span> <br>
            <table width="50%%" border="1" cellpadding="5" cellspacing="1" bgcolor='lightgray'>
                <tr>
                    <th>№ п/п</th>
                    <th>Ссылка</th>
                </tr>
                {% for i in range %}
                    <tr>
                        <td>{{ i }}</td>
                        <td> <a href="https://yandex.ru/search/?text={{i}}" target="_blank">Найти в яндекс: {{ i }}</a></td>
                    <tr>
                {% endfor %}
            </table>
            <span>END</span> <br> <br>
        {% else %}
            <p>Ветка ELSE</p>
            <span>START</span> <br>
            <table width="100%" border="1" cellpadding="5" cellspacing="1" bgcolor='lightgray'>
                <tr>
                    <th>Заголовок</th>
                    <th>Секция</th>
                    <th>Пользователь</th>
                    <th>Создано</th>
                    <th>Содержимое</th>
                    <th>Статус</th>
                </tr>
                {% for article in articles %}
                    <tr>
                        <td>{{ article.article_title }}</td>
                        <td>{{ article.article_section }}</td>
                        <td>{{ article.article_author }}</td>
                        <td>{{ article.article_date }}</td>
                        <td>{{ article.article_content }}</td>
                        <td>{{ article.article_status }}</td>
                    </tr>            
                {% endfor %}
            </table>
            <span>END</span> <br> <br>
        {% endif %}

        <form method="post">
            {% csrf_token %}
            <table>
                {{ bookForm }}            
                {{ userForm }}  
            </table>
            <br>
            <button type="submit" class="btn btn-success" name="print_btn">Save</button>
        </form>  
    {% endif %}  
{% endblock content %}


{% block header %}
    {% include "header.html" with name="Главная" %}
{% endblock header %}

{% block footer %}
    {% include "footer.html" %}
{% endblock footer %}

{% block nav %}    
    {% include "nav.html" with path="index" page="Index"%}
{% endblock nav %}

{% block asideLeft %}
    {% include "asideLeft.html" %}    
{% endblock asideLeft %}

{% block asideRight %}
    {% include "newmenu.html" with menu=menu %}    
{% endblock asideRight %}

mySite/headPage/templates/header.html
<span id="myHeader">{{name}}</span>
<hr id="myHeaderHr">

mySite/headPage/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <article>
        <h1>Количество записей {{ count }}</h1>
        {% if count > 0  %}
            <ul>
                {% for tovar in tovars %}
                    <li>Наименование: {{tovar.name}}</li>
                    <li>Описание: {{tovar.discript}}</li>
                    <li>Стоимость: {{tovar.cost}}</li>
                    <br>
                {% endfor %}
            </ul>
        {% else %}
            <h1>Нет записей</h1>
        {% endif %}
    </article>
{% endblock content %}

{% block header %}
    {% include "header.html" with name="Index" %}
{% endblock header %}

{% block footer %}
    {% include "footer.html" %}
{% endblock footer %}

{% block nav %}
    {% include "nav.html" %}
{% endblock nav %}

{% block aside %}
    <p>ASIDE</p>
{% endblock aside %}

{% block asideLeft %}
    {% include "asideLeft.html" %}    
{% endblock asideLeft %}

{% block asideRight %}
    {% include "asideRight.html" %}    
{% endblock asideRight %}

mySite/headPage/templates/nav.html
    <table >
        <tr>
            <th><a href="/">Главная</a></th>
            <th><a href="/index/">Index</a></th>
            <th><a href="/tovar/">Товар</a></th>
            <th><a href="/windy/">Windy</a></th>
            <th><a href="/admin/">Admin</a></th>
        </tr>
    </table>

mySite/headPage/templates/newmenu.html
{% for line in menu %}
    {% if line.level == 1 or line.first == 1 or line.visible %}        
        <form method="POST" class="myform">
        <input type="hidden" name="id" value={{ line.id }}> 
        <input type="hidden" name="l1" value={{ line.l1 }}>     
        <input type="hidden" name="l2" value={{ line.l2 }}>
        <input type="hidden" name="l3" value={{ line.l3 }}>
        <input type="hidden" name="l4" value={{ line.l4 }}>
        <input type="hidden" name="l5" value={{ line.l5 }}>
        <input type="hidden" name="first" value={{ line.first }}>
        <input type="hidden" name="visible" value={{ line.visible }}>
        <input type="hidden" name="content" value={{ line.content }}>
        <input type="hidden" name="level" value={{ line.level }}>
        <input type="hidden" name="link" value={{ line.link }}>
        {% csrf_token %}
        {% if line.level == 1 %}
            <button type='submit' class='allbuttons level_1' id='{{ line.id }}'>{{line.content}}</button>
        {% endif %}
        {% if line.level == 2 %}
            <button type='submit' class='allbuttons level_2' id='{{ line.id }}'>{{line.content}}</button>
        {% endif %}
        {% if line.level == 3 %}
            <button type='submit' class='allbuttons level_3' id='{{ line.id }}'>{{line.content}}</button>
        {% endif %}
        {% if line.level == 4 %}
            <button type='submit' class='allbuttons level_4' id='{{ line.id }}'>{{line.content}}</button>
        {% endif %}
        {% if line.level == 5 %}
            <button type='submit' class='allbuttons level_5' id='{{ line.id }}'>{{line.content}}</button>
        {% endif %}                   
        </form>        
    {% endif %}
{% endfor %}

mySite/headPage/templates/section.html
{% extends 'base.html' %}
{% block page %}
    <article>
    <h1>{{ section.section_title }}</h1>
        <p>{{ section.section_description|safe }}</p>
        <h2>Статьи</h2>
        <ul>
        {% for article in section.article_set.all|dictsort:'article_title' %}
            {% if article.article_status %}
            <li>
            <a href="{% url 'knowledge:article' section.section_url article.id %}">
                {{ article.article_title }}
            </a>
            </li>
            {% endif %}
        {% endfor %}
        </ul>
    </article>
{% endblock %} 
<!--#empty-->

mySite/headPage/templates/testPost.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Django Forms</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="Send" >
</form>
</body>
</html>

mySite/headPage/templates/tovar.html
{% extends 'base.html' %}
{% block content %}
    {% if id == -1 %}
        Введите данные:<br>
    {% endif %}
    {% if id == 1 %}
        Данные записанные в базу данных:<br>
        Наименование: {{ name }}<br>
        Описание: {{ discript }}<br>
        Стоимость: {{ cost }}<br>
    {% endif %}
    {% if id == 0 %}
        Запись с таким наименованием уже есть в базе данных<br>
    {% endif %}
    <form method="post">        
        {% csrf_token %}
        {{ form }}
        <br><br>
        <input type="submit" value="OK">
    </form>
{% endblock content %}

{% block header %}
    {% include "header.html" with name="Товар" %}
{% endblock header %}

{% block footer %}
    {% include "footer.html" %}
{% endblock footer %}

{% block nav %}    
    {% include "nav.html" %}
{% endblock nav %}

{% block asideLeft %}
    {% include "asideLeft.html" %}    
{% endblock asideLeft %}

{% block asideRight %}
    {% include "asideRight.html" %}    
{% endblock asideRight %}